In [39]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [40]:
from nltk.tokenize import word_tokenize
text="Natural language processing is amazing"
tokens=word_tokenize(text)
print(tokens)

['Natural', 'language', 'processing', 'is', 'amazing']


In [41]:

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [42]:
from nltk.corpus import stopwords

# Set of English stopwords
stop_words = set(stopwords.words('english'))

# Filter tokens using the correct variable stop_words
filtered = [word for word in tokens if word.lower() not in stop_words]

print(filtered)


['Natural', 'language', 'processing', 'amazing']


In [43]:
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()
print([stemmer.stem(word) for word in filtered])

['natur', 'languag', 'process', 'amaz']


In [44]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [45]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
print([lemmatizer.lemmatize(word) for word in filtered])


['Natural', 'language', 'processing', 'amazing']


In [46]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')


[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


True

In [47]:
import nltk
nltk.download('averaged_perceptron_tagger')
print(nltk.pos_tag(tokens))


[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


[('Natural', 'JJ'), ('language', 'NN'), ('processing', 'NN'), ('is', 'VBZ'), ('amazing', 'VBG')]


In [48]:
import spacy
nlp=spacy.load("en_core_web_sm")
doc=nlp("Apple was fonded y steve jobs")
for ent in doc.ents:
  print(ent.text,ent.label_)

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [ ]:
from sklearn.feature_extraction.text import CountVectorizor
from sklearn.naive_bayes import MultinomialNB
texts= ['i love this','buy now','limited offer']
labels=[0,1,1]
vectorizor=CountVectorizor()
X=vectorizor.fit_transform(texts)
model=MultinomialNB()
model.fit(X,labels)
print(model.predict(vectorizor.transform(['get rich quick'])))

In [ ]:
from textblob import TextBlob
blob=TextBlob(" i hate Mondays")
print(blob.sentiment)

In [ ]:
from gensim.models import Word2Vec

In [ ]:
from transformers import pipeline
classifier=pipeline("sentiment-analysis")
print(classifier("i love nlp langauge"))

In [ ]:
summarizer= pipeline("summarization")
text="yur long paragragh here.."
print(summarizer(text,max_length=50, min_length=25, do_sample=False))


In [ ]:
!pip install langdetect


In [ ]:
from langdetect import detect, detect_langs
text="C'est un bon restaurent"
language=detect(text)
print(f"Detected language:{language}")
print(detect_langs(text))

In [ ]:
!pip uninstall numpy -y
!pip install numpy


In [ ]:
!pip install gensim nltk


In [ ]:
from gensim.models import Word2Vec
import nltk
nltk.download('punkt')

# Sample data
text = "AI and machine learning are transforming the world. Generative models like ChatGPT are powerful tools."

# Tokenize sentence
tokens = nltk.word_tokenize(text.lower())

# Train Word2Vec model
model = Word2Vec([tokens], vector_size=100, window=5, min_count=1, workers=2)

# Get embedding for a word
embedding_ai = model.wv['ai']
print("Embedding for 'AI':\n", embedding_ai)


In [ ]:
!pip install googletrans==4.0.0-rc1


In [ ]:
!pip install googletrans==4.0.0-rc1


In [ ]:
from googlettrans import Translator
translator =Translator()
translated=translator.translate(text,src=language, dest='en')
print(translated.text)

In [ ]:
from transformers import pipeline
classifier = pipeline("text-classification", model="papluca/xlm-roberta-base-language-detection")
print(classifier("یہ بہت مزیدار تھا"))


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "The food was delicious and the service was excellent.",
    "I did not like the food at all.",
    "The restaurant had a cozy atmosphere.",
    "Service was okay but food was average.",
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

# Word scores for each document
print(vectorizer.get_feature_names_out())
print(X.toarray())


In [ ]:
# 📦 Step 1: Install & Import
!pip install scikit-learn matplotlib

from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
import numpy as np

# 📝 Step 2: Sample Reviews
corpus = [
    "The food was delicious and the service was excellent.",
    "I did not like the food at all.",
    "The restaurant had a cozy atmosphere.",
    "Service was okay but food was average."
]

# 🔢 Step 3: TF-IDF Vectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

# 🧠 Step 4: Vocabulary
words = vectorizer.get_feature_names_out()

# 📊 Step 5: Function to Plot Bar Chart for One Review
def plot_tfidf(review_index):
    scores = X[review_index].toarray()[0]
    top_indices = scores.argsort()[::-1][:7]  # Top 7 words
    top_words = [words[i] for i in top_indices]
    top_scores = [scores[i] for i in top_indices]

    plt.figure(figsize=(8, 4))
    plt.barh(top_words[::-1], top_scores[::-1], color='skyblue')
    plt.xlabel("TF-IDF Score")
    plt.title(f"Top Keywords in Review {review_index + 1}")
    plt.tight_layout()
    plt.show()

# ✨ Step 6: Plot Any Review (e.g., review 0)
plot_tfidf(0)


In [ ]:
!pip install nltk
!pip install gensim


In [ ]:
import nltk
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import warnings
warnings.filterwarnings("ignore")

In [ ]:
nltk.download('punkt')


In [ ]:
import nltk
nltk.download('punkt_tab')


In [ ]:
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt')

text = "I love mango. Mango is sweet. I also like apple and orange."
sentences = sent_tokenize(text)
data = [word_tokenize(sentence.lower()) for sentence in sentences]
print(data)


In [ ]:
# 📦 Step 1: Install gensim if needed
!pip install gensim

# 📥 Step 2: Imports
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt')
from gensim.models import Word2Vec

# 📝 Step 3: Prepare Data
text = "I love mango. Mango is sweet. I also like apple and orange."
sentences = sent_tokenize(text)
data = [word_tokenize(sentence.lower()) for sentence in sentences]

# 🤖 Step 4: Train Word2Vec Model
model = Word2Vec(sentences=data, vector_size=50, window=2, min_count=1, workers=4)

# 🔍 Step 5: Check Word Vector
print(model.wv['mango'])  # Vector for 'mango'


In [ ]:
print(model.wv['mango'])
print(model.wv.most_similar('mango'))

In [ ]:
# 📦 Step 1: Install gensim if needed (for Colab)
!pip install gensim

# 📥 Step 2: Imports
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from gensim.models import Word2Vec

nltk.download('punkt')

# 📝 Step 3: Prepare and tokenize your text
text = "I love mango. Mango is sweet. I also like apple and orange."
sentences = sent_tokenize(text)
data = [word_tokenize(sentence.lower()) for sentence in sentences]

# 🤖 Step 4: Train the Word2Vec model
model = Word2Vec(sentences=data, vector_size=50, window=2, min_count=1, workers=4)

# 🧬 Step 5: Get vector of a word
print("🔹 Word Vector for 'mango':")
print(model.wv['mango'])

# 🔍 Step 6: Find similar words to 'mango'
print("\n🔸 Words similar to 'mango':")
print(model.wv.most_similar('mango'))


In [ ]:
import numpy as np

arr = np.array(["apple", "banana", "cherry"])
print(arr)


In [ ]:
!pip install --upgrade numpy gensim nltk


In [ ]:
!pip install numpy==1.24.4


In [ ]:
# 📦 Install required libraries (Google Colab only)
!pip install gensim nltk

# 🔧 Import libraries
import gensim
from gensim.models import Word2Vec
from nltk.tokenize import sent_tokenize, word_tokenize
import nltk
import warnings
import zipfile

# 📥 Download tokenizers and suppress warnings
nltk.download('punkt')
warnings.filterwarnings('ignore')

# 📁 Load and clean text from ZIP file
with zipfile.ZipFile("/content/Gutenburg.zip", 'r') as zip_ref:
    file_name = zip_ref.namelist()[0]
    with zip_ref.open(file_name) as file:
        content = file.read().decode('utf-8', errors='ignore')
        cleaned_text = content.replace("\n", " ")
print("✅ File loaded and cleaned.")

# 🧹 Tokenization: sentence-level and word-level
data = []
for sentence in sent_tokenize(cleaned_text):
    words = [word.lower() for word in word_tokenize(sentence)]
    data.append(words)

# 🤖 Train Word2Vec models
model1 = Word2Vec(sentences=data, vector_size=100, window=5, min_count=1, sg=0)  # CBOW
model2 = Word2Vec(sentences=data, vector_size=100, window=5, min_count=1, sg=1)  # Skip-Gram

# 🧬 Compare cosine similarities using CBOW
print("\n🔹 Cosine similarity between 'alice' and 'wonderland' (CBOW):",
      model1.wv.similarity('alice', 'wonderland'))

print("🔸 Cosine similarity between 'alice' and 'machines' (CBOW):",
      model1.wv.similarity('alice', 'machines'))


In [ ]:
import nltk
import re

text = """Beans. I was trying to explain to somebody as we were flying in, that's corn.  That's beans. And they were very impressed at my agricultural knowledge. Please give it up for Amaury once again for that outstanding introduction. I have a bunch of good friends here today, including somebody who I served with, who is one of the finest senators in the country, and we're lucky to have him, your Senator, Dick Durbin is here. I also noticed, by the way, former Governor Edgar here, who I haven't seen in a long time, and somehow he has not aged and I have. And it's great to see you, Governor. I want to thank President Killeen and everybody at the U of I System for making it possible for me to be here today. And I am deeply honored at the Paul Douglas Award that is being given to me. He is somebody who set the path for so much outstanding public service here in Illinois. Now, I want to start by addressing the elephant in the room. I know people are still wondering why I didn't speak at the commencement."""

dataset = nltk.sent_tokenize(text)

for i in range(len(dataset)):
    dataset[i] = dataset[i].lower()
    dataset[i] = re.sub(r'\W', ' ', dataset[i])
    dataset[i] = re.sub(r'\s+', ' ', dataset[i])

for i, sentence in enumerate(dataset):
    print(f"Sentence {i+1}: {sentence}")

In [ ]:
word2count = {}

for data in dataset:
    words = nltk.word_tokenize(data)
    for word in words:
        if word not in word2count:
            word2count[word] = 1
        else:
            word2count[word] += 1

stop_words = set(stopwords.words('english'))

filtered_word2count = {word: count for word, count in word2count.items() if word not in stop_words}

word_freq_df = pd.DataFrame(list(filtered_word2count.items()), columns=['Word', 'Frequency'])

word_freq_df = word_freq_df.sort_values(by='Frequency', ascending=False)

print(word_freq_df)

In [ ]:
import heapq
import matplotlib.pyplot as plt

freq_words = heapq.nlargest(10, word2count, key=word2count.get)

print(f"Top 10 frequent words: {freq_words}")

top_words = sorted(word2count.items(), key=lambda x: x[1], reverse=True)[:10]
words, counts = zip(*top_words)

plt.figure(figsize=(10, 6))
plt.bar(words, counts, color='skyblue')
plt.xticks(rotation=45)
plt.title('Top 10 Most Frequent Words')
plt.xlabel('Words')
plt.ylabel('Frequency')
plt.show()

In [ ]:
!pip install seaborn

In [49]:
!pip install numpy==1.24.4 matplotlib==3.7.1 seaborn==0.12.2 --force-reinstall



  Using cached numpy-1.24.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.9/107.9 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 7.4 MB/s eta 0:00:00
Using cached numpy-1.24.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 36.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 326.2/326.2 kB 20.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 41.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 55.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 16.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 52.6 MB/s eta 0:00:00
   ━━━━━━━

In [50]:
import numpy as np
import seaborn as sns

X = []

for data in dataset:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(data):
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)

X = np.asarray(X)

plt.figure(figsize=(10, 6))
sns.heatmap(X, cmap='RdYlGn', cbar=False, annot=True, fmt="d", xticklabels=freq_words, yticklabels=[f"Sentence {i+1}" for i in range(len(dataset))])

plt.title('Bag of Words Matrix')
plt.xlabel('Frequent Words')
plt.ylabel('Sentences')
plt.show()

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [1]:
from wordcloud import WordCloud

wordcloud = WordCloud(width=800, height=400, background_color='white').generate_from_frequencies(word2count)

plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Word Cloud of Frequent Words")
plt.show()

NameError: name 'word2count' is not defined

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

# 📝 Sample text
corpus = [
    "Alice loves wonderland",
    "Wonderland is full of surprises",
    "Alice enjoys surprises too"
]

# 🔢 Create BoW model
vectorizer = CountVectorizer()

# 📊 Convert text to vector form
X = vectorizer.fit_transform(corpus)

# 📁 Show feature matrix
print("Vocabulary:", vectorizer.vocabulary_)
print("BoW Matrix:\n", X.toarray())


Vocabulary: {'alice': 0, 'loves': 4, 'wonderland': 8, 'is': 3, 'full': 2, 'of': 5, 'surprises': 6, 'enjoys': 1, 'too': 7}
BoW Matrix:
 [[1 0 0 0 1 0 0 0 1]
 [0 0 1 1 0 1 1 0 1]
 [1 1 0 0 0 0 1 1 0]]


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# 🧾 Example dataset
data = {
    'label': ['ham', 'spam', 'ham', 'spam'],
    'message': [
        "Let's catch up for lunch today",
        "Congratulations! You've won a free ticket. Claim now!",
        "Meeting at 3 PM, don't be late",
        "You have won $1000! Call this number now"
    ]
}

# 📊 Convert to DataFrame
df = pd.DataFrame(data)

# 🛠️ Initialize CountVectorizer
vectorizer = CountVectorizer()

# 🔢 Transform messages into BoW features
X = vectorizer.fit_transform(df['message'])

# 📁 Show vocabulary and BoW matrix
print("Vocabulary:\n", vectorizer.vocabulary_)
print("\nBoW Matrix:\n", X.toarray())


Vocabulary:
 {'let': 12, 'catch': 4, 'up': 21, 'for': 8, 'lunch': 13, 'today': 20, 'congratulations': 6, 'you': 24, 've': 22, 'won': 23, 'free': 9, 'ticket': 19, 'claim': 5, 'now': 15, 'meeting': 14, 'at': 1, 'pm': 17, 'don': 7, 'be': 2, 'late': 11, 'have': 10, '1000': 0, 'call': 3, 'this': 18, 'number': 16}

BoW Matrix:
 [[0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1]
 [0 1 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 1]]


In [6]:
!pip install gensim.models

ERROR: Could not find a version that satisfies the requirement gensim.models (from versions: none)
ERROR: No matching distribution found for gensim.models


In [5]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

sentences = [
    word_tokenize("Alice loves wonderland"),
    word_tokenize("Alice chases the rabbit"),
    word_tokenize("Wonderland is magical")
]

# Train Word2Vec
model = Word2Vec(sentences, vector_size=50, window=2, min_count=1, sg=1)  # sg=1 means Skip-Gram

# Similarity check
print("Similarity between 'alice' and 'wonderland':", model.wv.similarity('alice', 'wonderland'))


ModuleNotFoundError: No module named 'gensim'